[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RCPSPSandbox"
version = "0.0.1"
description = ""
readme = "README"
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/Krtiiik/RCPSPSandbox"
